name: Trigger Build on Comment

on:
  issue_comment:
    types: [created, edited]

jobs:
  check-build:
    #if: ${{ startsWith(github.event.comment.body, '/run-build') }}
    runs-on: ubuntu-latest
    steps:
      - name: print body
        env:
          BODY: ${{ github.event.comment.body }}
        run: echo "$BODY"
